[[startin]]
arch = "aarch64"
git-tree-sha1 = "0be19523d1477e3dac35e746202ff76f82d38f1f"
os = "macos"

    [[startin.download]]
    sha256 = "0121787a9421bf4ec9d1e5d4bbc6053e140ac57690ad96f22b26d6c3fac0c9d6"
    url = "https://github.com/JuliaBinaryWrappers/startin_jll.jl/releases/download/startin-v0.5.3+0/startin.v0.5.3.aarch64-apple-darwin.tar.gz"
[[startin]]
arch = "aarch64"
git-tree-sha1 = "08003f6684457930307abbcb7a261aa3362ceaf8"
libc = "glibc"
os = "linux"

    [[startin.download]]
    sha256 = "4fb5333f79a6f02b0b515df0fd4e0d6a1f8e3242da2985eca3944fefe1f66ae4"
    url = "https://github.com/JuliaBinaryWrappers/startin_jll.jl/releases/download/startin-v0.5.3+0/startin.v0.5.3.aarch64-linux-gnu.tar.gz"
[[startin]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "12fbcd9d0c46a817f17bda09f950bd07eb82d49b"
libc = "glibc"
os = "linux"

    [[startin.download]]
    sha256 = "cca49aac00ea79facda907c064ce1039d0f6608c5d74cad5d012f05009e2e1bd"
    url = "https://github.com/JuliaBinaryWrappers/startin_jll.jl/releases/download/startin-v0.5.3+0/startin.v0.5.3.armv6l-linux-gnueabihf.tar.gz"
[[startin]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2b7ff62bc2efac90c5e298c064bbf4cd2906e013"
libc = "glibc"
os = "linux"

    [[startin.download]]
    sha256 = "58931219834a82ff9a2f02b5028a90602163c77beba0566fccb1db56d0eb61d2"
    url = "https://github.com/JuliaBinaryWrappers/startin_jll.jl/releases/download/startin-v0.5.3+0/startin.v0.5.3.armv7l-linux-gnueabihf.tar.gz"
[[startin]]
arch = "i686"
git-tree-sha1 = "2feeddc43ca7d597c10d37268eecfb97da9973c1"
libc = "glibc"
os = "linux"

    [[startin.download]]
    sha256 = "7f3b9058f8538e55ade8bbc0101cf1c3cc8ae6f54ea2c2a8f705425c6f3b9e23"
    url = "https://github.com/JuliaBinaryWrappers/startin_jll.jl/releases/download/startin-v0.5.3+0/startin.v0.5.3.i686-linux-gnu.tar.gz"
[[startin]]
arch = "powerpc64le"
git-tree-sha1 = "f3d93cc93cccafd703ffa9a955931db226e345e3"
libc = "glibc"
os = "linux"

    [[startin.download]]
    sha256 = "57c0cf3bb86b8dede08e1fafd83ea4deeea7852559c6e84652d42e04bdc893cc"
    url = "https://github.com/JuliaBinaryWrappers/startin_jll.jl/releases/download/startin-v0.5.3+0/startin.v0.5.3.powerpc64le-linux-gnu.tar.gz"
[[startin]]
arch = "x86_64"
git-tree-sha1 = "b9b8f968e71e58316f32e0d4b996525f8d546e4f"
os = "macos"

    [[startin.download]]
    sha256 = "f001fddd6f35914bc63503fe3dbb5d4e1c3cbc561ee186808cee129075808494"
    url = "https://github.com/JuliaBinaryWrappers/startin_jll.jl/releases/download/startin-v0.5.3+0/startin.v0.5.3.x86_64-apple-darwin.tar.gz"
[[startin]]
arch = "x86_64"
git-tree-sha1 = "0d6d6a5e1b799f417e225ddbbbecff50c8cf15a4"
libc = "glibc"
os = "linux"

    [[startin.download]]
    sha256 = "22a689ae1916559eadc66f86832d37299eb112661f4e0ee729216e929f9df7d1"
    url = "https://github.com/JuliaBinaryWrappers/startin_jll.jl/releases/download/startin-v0.5.3+0/startin.v0.5.3.x86_64-linux-gnu.tar.gz"
[[startin]]
arch = "x86_64"
git-tree-sha1 = "f15413ce1d07c9d7d9eae5b2c2a63a6e31d05bf1"
os = "freebsd"

    [[startin.download]]
    sha256 = "0117bf2dae0393cc8d61d1ae0c015fdefded55503dbd40970ba638e6a38c9a4e"
    url = "https://github.com/JuliaBinaryWrappers/startin_jll.jl/releases/download/startin-v0.5.3+0/startin.v0.5.3.x86_64-unknown-freebsd.tar.gz"
[[startin]]
arch = "x86_64"
git-tree-sha1 = "146cb8808dc522dc17c30d286a5a69c65f06bbb8"
os = "windows"

    [[startin.download]]
    sha256 = "5e8f8a690604b682ac1c59d3763753562be46f4ea844e55590efc5878183a459"
    url = "https://github.com/JuliaBinaryWrappers/startin_jll.jl/releases/download/startin-v0.5.3+0/startin.v0.5.3.x86_64-w64-mingw32.tar.gz"
