# Autogenerated wrapper script for startin_jll for x86_64-apple-darwin
export libstartin

JLLWrappers.@generate_wrapper_header("startin")
JLLWrappers.@declare_library_product(libstartin, "@rpath/libstartin.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libstartin,
        "lib/libstartin.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
